### ISSUE TITLE
PurchaseObject incorrect non optional field

### ISSUE THREAD

**Issue by vitaly-furman** [braze-community/braze-node#600]
## Expected Behavior

PurchaseObject.app_id should be optional

https://www.braze.com/docs/api/objects_filters/purchase_object/

## Actual Behavior

PurchaseObject.app_id is required, therefore not letting send track user purchase without app_id

## Steps to Reproduce

```
interface PurchaseObject {
    external_id?: string;
    user_alias?: UserAlias;
    braze_id?: string;
    app_id: string;
    product_id: string;
    currency: string;
    price: number;
    quantity?: number;
    time: string;
    properties?: Properties;
    _update_existing_only?: boolean;
}
```
## Reproducible Demo

Can just change `app_id` to optional:

```
interface PurchaseObject {
    external_id?: string;
    user_alias?: UserAlias;
    braze_id?: string;
    app_id?: string;
    product_id: string;
    currency: string;
    price: number;
    quantity?: number;
    time: string;
    properties?: Properties;
    _update_existing_only?: boolean;
}
```

## Environment

- Version: 2.7.0
- Platform:
- Browser:
- OS:

## Keywords

trackUserObject, PurchaseObject, app_id

**Comment by remarkablemark** [comment]
Release:

- https://github.com/braze-community/braze-node/pull/602#issuecomment-2076079516
