### ISSUE TITLE
Missing android_push and apple_push types

### ISSUE THREAD

**Issue by lawandothman** [braze-community/braze-node#614]
## Problem

Hey, thanks for your work on this library - it's been super helpful!

I noticed that both `apple_push` and `android_push` are typed as objects in the [`MessageObject` interface](https://github.com/braze-community/braze-node/blob/master/src/messages/types.ts#L30-L31). 

It would be cool if we can get full type support for both of these objects as demonstrated here: 
* [Apple object](https://www.braze.com/docs/api/objects_filters/messaging/apple_object/)
* [Android object](https://www.braze.com/docs/api/objects_filters/messaging/android_object/)

## Suggested Solution

I'm happy to contribute and raise a PR for this but just wanted to raise an issue first in case it's on your radar or working on it

**Comment by remarkablemark** [comment]
@lawandothman Thanks for opening this issue, a PR would be greatly appreciated!
