### ISSUE TITLE
Missing segment support

### ISSUE THREAD

**Issue by joeraut** [braze-community/braze-node#665]
## Problem

Many thanks for this library! I noticed it is missing support for segments:
- /segments/list
- /segments/data_series
- /segments/details

## Suggested Solution
I'm happy to contribute and raise a PR for this but just wanted to raise an issue first in case it's on your radar or working on it.

**Comment by remarkablemark** [comment]
Release:

- https://github.com/braze-community/braze-node/pull/667#issuecomment-2250815853
